### ISSUE TITLE
An error pop-up

### ISSUE THREAD

**Issue by virologist** [Jay-Squared/QuotationsToolbox#19]
Hi, @Jay-Squared 
An error has occurred when I adding quotations. 
Snapshot and details are given below.

![image](https://user-images.githubusercontent.com/54756814/137590437-5d27e299-5f16-4d58-90be-2b35a92e5e5a.png)

```
Technical Information for the Citavi Team:
pdftron.Common.PDFNetException: Exception: 
	 Message: Doc root not found
	 Conditional expression: root
	 Version      : 8.1.1.76963
	 Platform     : .Net Framework
	 Architecture : AMD64
	 Filename     : SDFDocImpl.cpp
	 Function     : trn::SDF::DocImpl::GetRoot
	 Linenumber   : 954

   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.WindowsFormsSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at SwissAcademic.Collections.NotificationCollection`1.OnCollectionChanged(CollectionChangedEventArgs`1 e)
   at SwissAcademic.Citavi.ReferenceQuotationCollection.OnCollectionChanged(CollectionChangedEventArgs`1 e)
   at SwissAcademic.Collections.NotificationCollection`1.ResumeNotification(Boolean raisePendingEvents, Boolean force)
   at SwissAcademic.Collections.NotificationCollection`1.RemoveItemRange(IEnumerable`1 collection, Boolean performChecks)
   at SwissAcademic.Citavi.Shell.MainForm.Delete(Control activeControl, Boolean silent)
   at SwissAcademic.Citavi.Shell.MainForm.<PerformCommand>d__980.MoveNext()
```

By the way, could you please add the markdown format exportation to match the need for backlinks (Bi-directional links, like roam research, obsidian, logseq, and so on) since these kinds of note-app are more and more popular and powerful to organize the note knowledge?

Best wishes,
Yang

**Comment by Jay-Squared** [comment]
I can't replicate that issue. What are the precise steps necessary to reproduce it?

I don't understand the feature request (which should be it’s own post so that it can be tracked), so it is unlikely that I would implement that.
